# # Definitions of tags to detect
#
# ## General remarks
#
# - All length in meters
# - Ellipsis (...) signifies that the previous element can be repeated multiple times.
#
# ## Standalone tag definitions
# ### Remarks
#
# - name is optional
#
# ### Syntax
#
# standalone_tags:
#   [
#     {id: ID, size: SIZE, name: NAME},
#     ...
#   ]
standalone_tags:
  [
{ id: 0, size: 0.143,name: 'my_bundle' },
{ id: 1, size: 0.143,name: 'my_bundle' },
{ id: 2, size: 0.143,name: 'my_bundle' },
{ id: 3, size: 0.143,name: 'my_bundle' },
{ id: 4, size: 0.143,name: 'my_bundle' },
{ id: 5, size: 0.143,name: 'my_bundle' },
{ id: 6, size: 0.143,name: 'my_bundle' },
{ id: 7, size: 0.143,name: 'my_bundle' },
{ id: 8, size: 0.143,name: 'my_bundle' },
{ id: 9, size: 0.143,name: 'my_bundle' },
{ id: 11, size: 0.143,name: 'my_bundle' },
{ id: 12, size: 0.143,name: 'my_bundle' },
{ id: 13, size: 0.143,name: 'my_bundle' },
{ id: 14, size: 0.143,name: 'my_bundle' },
{ id: 15, size: 0.143,name: 'my_bundle' },
{ id: 16, size: 0.143,name: 'my_bundle' },
{ id: 17, size: 0.143,name: 'my_bundle' },
{ id: 18, size: 0.143,name: 'my_bundle' },
{ id: 19, size: 0.143,name: 'my_bundle' },
{ id: 20, size: 0.143,name: 'my_bundle' },
{ id: 21, size: 0.143,name: 'my_bundle' },
{ id: 22, size: 0.143,name: 'my_bundle' },
{ id: 23, size: 0.143,name: 'my_bundle' },
{ id: 24, size: 0.143,name: 'my_bundle' },
{ id: 25, size: 0.143,name: 'my_bundle' },
{ id: 26, size: 0.143,name: 'my_bundle' },
{ id: 27, size: 0.143,name: 'my_bundle' },
{ id: 28, size: 0.143,name: 'my_bundle' },
{ id: 29, size: 0.143,name: 'my_bundle' },
{ id: 30, size: 0.143,name: 'my_bundle' },
{ id: 31, size: 0.143,name: 'my_bundle' },
{ id: 32, size: 0.143,name: 'my_bundle' },
{ id: 33, size: 0.143,name: 'my_bundle' },
{ id: 34, size: 0.143,name: 'my_bundle' },
  ]
# ## Tag bundle definitions
# ### Remarks
#
# - name is optional
# - x, y, z have default values of 0 thus they are optional
# - qw has default value of 1 and qx, qy, qz have default values of 0 thus they are optional
#
# ### Syntax
#
# tag_bundles:
#   [
#     {
#       name: 'CUSTOM_BUNDLE_NAME',
#       layout:
#         [
#           {id: ID, size: SIZE, x: X_POS, y: Y_POS, z: Z_POS, qw: QUAT_W_VAL, qx: QUAT_X_VAL, qy: QUAT_Y_VAL, qz: QUAT_Z_VAL},
#           ...
#         ]
#     },
#     ...
#   ]
tag_bundles:
  [
  ]
